apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-corrupt
  namespace: gateway
spec:
  action: corrupt
  mode: all
  selector:
    namespaces:
      - gateway
    labelSelectors:
      app: gateway
  corrupt:
    corrupt: '20'
    correlation: '20'
  direction: to
