apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-telemetry-gateway
  namespace: gateway
  labels:
    app: llm-telemetry-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-telemetry-gateway
  template:
    metadata:
      labels:
        app: llm-telemetry-gateway
    spec:
      containers:
      # 1. Go Proxy Data Plane Container
      - name: gateway
        image: alpine:3.20
        command: ["/app/bin/gateway"]
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector.telemetry.svc.cluster.local:4317"
        volumeMounts:
        - name: shared-uds
          mountPath: /tmp/shared
        - name: project-code
          mountPath: /app
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

      # 2. Python Policy Sidecar Container
      - name: sidecar
        image: python:3.13-slim
        command: ["python", "/app/cmd/sidecar/policy.py"]
        volumeMounts:
        - name: shared-uds
          mountPath: /tmp/shared
        - name: project-code
          mountPath: /app
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

      volumes:
      - name: shared-uds
        emptyDir:
          medium: Memory
      - name: project-code
        hostPath:
          path: /var/home/victoriac/software/llm-telemetry-gateway
          type: Directory
