apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: cpu-stress
  namespace: gateway
spec:
  mode: all
  selector:
    namespaces:
      - gateway
    labelSelectors:
      app: gateway
  stressors:
    cpu:
      workers: 2
      load: 80
  duration: '5m'
