apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: memory-stress
  namespace: gateway
spec:
  mode: all
  selector:
    namespaces:
      - gateway
    labelSelectors:
      app: gateway
  stressors:
    memory:
      workers: 1
      size: '256MB'
  duration: '5m'
