apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill
  namespace: gateway
spec:
  action: pod-kill
  mode: all
  selector:
    namespaces:
      - gateway
    labelSelectors:
      app: gateway
