apiVersion: chaos-mesh.org/v1alpha1
kind: HTTPChaos
metadata:
  name: http-abort
  namespace: gateway
spec:
  mode: all
  selector:
    namespaces:
      - gateway
    labelSelectors:
      app: gateway
  target: Request
  port: 8080
  path: /v1/chat/completions
  abort: true
  code: 500
