name: Continuous Integration

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.go'
      - '**/*.py'
      - 'go.mod'
      - 'go.sum'
      - 'requirements.txt'
      - 'k3s/**/*.yaml'
      - 'k3s/**/*.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.go'
      - '**/*.py'
      - 'go.mod'
      - 'go.sum'
      - 'requirements.txt'
      - 'k3s/**/*.yaml'
      - 'k3s/**/*.yml'

env:
  python-version: '3.13'
  go-version: '1.26'

jobs:
  changes:
    name: Detect File Changes
    runs-on: ubuntu-latest
    outputs:
      go: ${{ steps.filter.outputs.go }}
      python: ${{ steps.filter.outputs.python }}
      k3s: ${{ steps.filter.outputs.k3s }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            go:
              - '**/*.go'
              - 'go.mod'
              - 'go.sum'
            python:
              - '**/*.py'
              - 'requirements.txt'
            k3s:
              - 'k3s/**/*.yaml'
              - 'k3s/**/*.yml'

  python-ci:
    name: Python Lint & Test
    needs: changes
    if: ${{ needs.changes.outputs.python == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ env.python-version }}
          cache: 'pip'

      - name: Install Python Dependencies
        run: |
          make install

      - name: Run Python Linting
        run: |
          make lint-py

      - name: Run Python Unit Tests
        run: |
          make test-py

  go-ci:
    name: Go Lint & Test
    needs: changes
    if: ${{ needs.changes.outputs.go == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.go-version }}
          cache: true

      - name: Run Go Linting
        run: |
          make lint-go

      - name: Run Go Unit Tests
        run: |
          make test-go

  k3s-ci:
    name: Kubernetes Lint
    needs: changes
    if: ${{ needs.changes.outputs.k3s == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: stackrox/kube-linter-action@v1
        with:
          directory: k3s
          config: .kube-linter.yaml
