name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  python-version: '3.13'
  go-version: '1.26'

jobs:
  changes:
    name: Detect File Changes
    runs-on: ubuntu-latest
    outputs:
      go: ${{ steps.filter.outputs.go }}
      e2e: ${{ steps.filter.outputs.e2e }}
      python: ${{ steps.filter.outputs.python }}
      k3s: ${{ steps.filter.outputs.k3s }}
      markdown: ${{ steps.filter.outputs.markdown }}
    steps:
      - uses: actions/checkout@v7
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            go:
              - '**/*.go'
              - 'go.mod'
              - 'go.sum'
            e2e:
              - 'e2e/**'
              - 'internal/gateway/**'
              - 'cmd/gateway/**'
              - 'go.mod'
              - 'go.sum'
            python:
              - '**/*.py'
              - 'pyproject.toml'
              - 'uv.lock'
            k3s:
              - 'k3s/**/*.yaml'
              - 'k3s/**/*.yml'
            markdown:
              - '**/*.md'

  app-ci:
    name: App Lint & Test
    needs: changes
    if: ${{ needs.changes.outputs.python == 'true' || needs.changes.outputs.go == 'true' || needs.changes.outputs.e2e == 'true' || needs.changes.outputs.markdown == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version: ${{ env.go-version }}
          cache: true

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: ${{ env.python-version }}

      - name: Install Python Dependencies
        run: |
          make install

      - name: Run Linters
        run: |
          make lint

      - name: Run Python Unit Tests
        if: ${{ needs.changes.outputs.python == 'true' }}
        run: |
          make test-py

      - name: Run Go Unit Tests
        if: ${{ needs.changes.outputs.go == 'true' }}
        run: |
          make test-go

      - name: Run Go BDD E2E Tests
        if: ${{ needs.changes.outputs.e2e == 'true' }}
        run: |
          make test-bdd

  k3s-ci:
    name: Kubernetes Lint
    needs: changes
    if: ${{ needs.changes.outputs.k3s == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: stackrox/kube-linter-action@v1
        with:
          directory: k3s
          config: .kube-linter.yaml
